version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebooks
    volumes:
      - .:/app
      - ../.cache:/root/.cache
    tty: true
    shm_size: "16gb"
    deploy:
      resources:
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA
                - video # NVDEC/NVENC/NVCUVID. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
